{"frames":[{"func":"eqdist.nn(z, N, k)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"boot(data = z, statistic = Tn, R = R, sim = \"permutation\", sizes = sizes, \n    k = k)","file":"","line_number":2,"end_line_number":3,"character_number":3,"end_character_number":39},{"func":"lapply(seq_len(RR), fn)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"FUN(X[[i]], ...)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"statistic(data, i[r, ], ...)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"nn2(data = z, k = k + 1)","file":"","line_number":5,"end_line_number":5,"character_number":1,"end_character_number":24}],"message":"Error in base::try(o, TRUE) : 找不到对象'o'\n"}